# Generated by Django 2.2.7 on 2019-11-14 03:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('autores', '0001_initial'),
        ('editoriales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('fecha_publicacion', models.DateField(default=datetime.datetime(2019, 11, 14, 3, 10, 53, 272513, tzinfo=utc))),
                ('autores', models.ManyToManyField(to='autores.Autor')),
                ('editorial', models.ForeignKey(on_delete=True, to='editoriales.Editorial')),
            ],
        ),
    ]
